#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.0.0f
PACKAGE_DEPEND=()

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://www.openssl.org/source/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			cp -rlf ../${G_SOURCE}/* ./
			CC="agcc.bash" LD="agcc.bash" RANLIB="${G_RANLIB}" \
			./Configure linux-generic32 zlib-dynamic no-idea no-bf no-cast no-seed no-md2 -DL_ENDIAN \
				--prefix=/system \
				--openssldir=/system/etc/ssl
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT} depend MAKEDEPPROG="agcc.bash -E -MM"
		${G_MAKE} -C ${G_OBJECT} -j1
		${G_MAKE} -C ${G_OBJECT} -j1 install INSTALL_PREFIX=$(pwd)/${G_EXPORT}
		mkdir -p ${G_EXPORT}/system/share
		mv ${G_EXPORT}/system/etc/ssl/man ${G_EXPORT}/system/share/
		chmod -R 0710 ${G_EXPORT}/system/etc/ssl/private
		rm -r ${G_EXPORT}/system/lib/pkgconfig
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* || true
		touch ${G_EXPORT}/.d
	fi
}
