#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.0.1
PACKAGE_DEPEND=()

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://www.openssl.org/source/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			cp -rlf ../${G_SOURCE}/* ./
			CC="${G_CC}" LD="${G_CC}" RANLIB="${G_RANLIB}" \
			./Configure linux-generic32 shared zlib-dynamic no-idea no-bf no-cast no-seed no-md2 -DL_ENDIAN ${G_ALL_CFLAGS} \
				--prefix=${G_INSTALLPREFIX} \
				--openssldir=${G_INSTALLPREFIX}/etc/ssl
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT} depend MAKEDEPPROG="${G_CC} -E -MM"
		${G_MAKE} -C ${G_OBJECT} -j1
		${G_MAKE} -C ${G_OBJECT} -j1 install INSTALL_PREFIX=$(pwd)/${G_EXPORT}
		mkdir -p ${G_EXP_SYSDIR}/share
		mv ${G_EXP_SYSDIR}/etc/ssl/man ${G_EXP_SYSDIR}/share/
		chmod -R 0710 ${G_EXP_SYSDIR}/etc/ssl/private
		chmod -R 0755 ${G_EXP_LIBDIR}/*.so.* ${G_EXP_LIBDIR}/engines/*
		${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* ${G_EXP_LIBDIR}/*.so.* ${G_EXP_LIBDIR}/engines/* || true
		botbrew_fix_interpreter_path ${G_EXPORT}
		touch ${G_EXPORT}/.d
	fi
}
