#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=4.7.0
PACKAGE_DEPEND=( binutils gmp mpfr mpc ppl cloog )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.bz2

botbrew_do_build() {
	botbrew_download http://ftp.gnu.org/gnu/${PACKAGE_NAME}/${FULLNAME}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_patchtree -p0 ${G_SOURCE} patch/gcc-4.7.0-android.patch
	botbrew_import
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CFLAGS="${G_CPPFLAGS} ${G_ALL_CFLAGS}" CXXFLAGS="${G_CPPFLAGS} ${G_ALL_CXXFLAGS}" \
			LDFLAGS="-Wl,-rpath-link,${G_LIBDIR}" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} --target=${G_TRIPLET} \
				--with-host-libstdcxx="-lstdc++" \
				--enable-languages=c \
				--with-system-zlib \
				--disable-sjlj-exceptions \
				--disable-libgomp \
				--with-gmp=${G_SYSDIR} \
				--with-mpfr=${G_SYSDIR} \
				--with-mpc=${G_SYSDIR} \
				--with-ppl=${G_SYSDIR} \
				--with-cloog=${G_SYSDIR} \
				--enable-cloog-backend=isl
			mkdir gcc
			cp ../${G_SOURCE}/gcc/ginclude/unwind-arm-common.h gcc/
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} -j1 install DESTDIR=$(pwd)/${G_EXPORT}
		cp -r ${G_NDKPATH}/platforms/android-${G_NDKAPI}/arch-arm/usr/lib/*.o ${G_EXP_LIBDIR}/gcc/${G_TRIPLET}/${PACKAGE_VERSION}/
		cp -rlf ${G_EXP_LIBDIR}/gcc/${G_TRIPLET}/4.4.3/* ${G_EXP_LIBDIR}/gcc/${G_TRIPLET}/${PACKAGE_VERSION}/
		rm -r ${G_EXP_LIBDIR}/gcc/${G_TRIPLET}/4.4.3
		${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* $(find ${G_EXPORT} -name '*.so*') \
			$(find ${G_EXP_SYSDIR}/libexec/gcc/${G_TRIPLET}/${PACKAGE_VERSION}) || true
		botbrew_fix_interpreter_path ${G_EXPORT}
		touch ${G_EXPORT}/.d
	fi
}
