#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=0.0.1
PACKAGE_DEPEND=( xorg-proto xorg-lib-libxau )

local DLPREFIX=http://xcb.freedesktop.org/dist
local PART=(
	xcb-proto-1.7
	libpthread-stubs-0.3
	libxcb-1.8
#	xcb-util-0.3.8
#	xcb-util-image-0.3.8
#	xcb-util-keysyms-0.3.8
#	xcb-util-renderutil-0.3.8
#	xcb-util-wm-0.3.8
)

botbrew_do_build() {
	mkdir -p ${G_OBJECT} ${G_SOURCE} ${G_EXPORT}
	botbrew_import
	local CWD=$(pwd)
	local INCFLAGS="-I${G_INCDIR} -I$(pwd)/${G_EXPORT}/system/include"
	local LIBFLAGS="-L${G_LIBDIR} -L$(pwd)/${G_EXPORT}/system/lib"
	for item in ${PART[@]}; do
		botbrew_download ${DLPREFIX}/${item}.tar.bz2 ${item}.tar.bz2
		botbrew_unpack ${item}.tar.bz2 ${item} || true
		botbrew_copytree ${item}/${item} ${G_SOURCE}/${item} || true
		botbrew_fix_config ${G_SOURCE}/${item} || true
		case ${item} in
			libxcb-*)
				botbrew_patchtree -p0 ${G_SOURCE}/${item} patch/libxcb-1.8-android.patch
				;;
		esac
		if ! [ -e ${G_OBJECT}/${item}/Makefile ]; then
			(
				mkdir -p ${G_OBJECT}/${item}; cd ${G_OBJECT}/${item}
				CC="agcc.bash" LD="agcc.bash" \
				XCBPROTO_CFLAGS="${INCFLAGS}" XCBPROTO_LIBS="${LIBFLAGS}" \
				XCB_CFLAGS="${INCFLAGS}" XCB_LIBS="${LIBFLAGS}" \
				NEEDED_CFLAGS="${INCFLAGS}" NEEDED_LIBS="${LIBFLAGS}" \
				XCBPROTO_XCBPYTHONDIR=${G_EXPORT} \
				../../${G_SOURCE}/${item}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET}
			)
		fi
		if ! [ -e ${G_EXPORT}/.d.${item} ]; then
			${G_MAKE} -C ${G_OBJECT}/${item} \
				XCBPROTO_XCBPYTHONDIR=${CWD}/${G_OBJECT}/${item} \
				XCBPROTO_XCBINCLUDEDIR=${CWD}/${G_EXPORT}/system/share/xcb
			${G_MAKE} -C ${G_OBJECT}/${item} install DESTDIR=${CWD}/${G_EXPORT}
			touch ${G_EXPORT}/.d.${item}
		fi
	done
	if ! [ -e ${G_EXPORT}/.d ]; then
		rm -rf ${G_EXPORT}/system/lib/*.la ${G_EXPORT}/system/lib/pkgconfig
		touch ${G_EXPORT}/.d
	fi
}
