#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=6.2
PACKAGE_DEPEND=( ncursesw )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://ftp.gnu.org/gnu/${PACKAGE_NAME}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_fix_config ${G_SOURCE}/support
	if ! [ -e ${G_SOURCE}/.do.ncursesw ]; then
		sed -e 's/ncurses/ncursesw/g' ${G_SOURCE}/configure > temp
		cat temp > ${G_SOURCE}/configure
		sed -e 's/ncurses/ncursesw/g' ${G_SOURCE}/aclocal.m4 > temp
		mv temp ${G_SOURCE}/aclocal.m4
		touch ${G_SOURCE}/.do.ncursesw
	fi
	botbrew_patchtree -p0 ${G_SOURCE} patch/readline-6.2-android.patch
	botbrew_import
	botbrew_fix_crosslibconfig ${G_SYSDIR}/bin/ncursesw5-config
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CPPFLAGS="-I${G_INCDIR} ${G_CPPFLAGS} ${G_ALL_CFLAGS}" LDFLAGS="-L${G_LIBDIR}" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
				--with-shared
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT} SHLIB_LIBS="-lncursesw"
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		chmod 0755 ${G_EXP_LIBDIR}/*.so*
		${G_STRIP} --strip-unneeded ${G_EXP_LIBDIR}/*.so* || true
		touch ${G_EXPORT}/.d
	fi
}
