#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=2010
PACKAGE_DEPEND=()

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_git git://git.ghostscript.com/thirdparty/${PACKAGE_NAME}.git ${PACKAGE_NAME}
	botbrew_copytree ${PACKAGE_NAME} ${G_SOURCE} || true
	botbrew_import
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			cp -rlf ../${G_SOURCE}/* ./
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT} CC="agcc.bash"
		mkdir -p ${G_EXPORT}/system/bin ${G_EXPORT}/system/lib ${G_EXPORT}/system/include
		cp -lf ${G_OBJECT}/jpegxr ${G_EXPORT}/system/bin/
		cp -lf ${G_OBJECT}/libjpegxr.a ${G_EXPORT}/system/lib/
		cp -lf ${G_SOURCE}/jpegxr.h ${G_EXPORT}/system/include/
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* || true
		touch ${G_EXPORT}/.d
	fi
}
