#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.7.10.rc0
PACKAGE_DEPEND=( openssl )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://git-core.googlecode.com/files/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	sed -E 's/as_fn_error (\$\? "cannot run test program)/$as_echo \1/g' ${G_SOURCE}/configure > temp
	cat temp > ${G_SOURCE}/configure
	rm temp
#	botbrew_patchtree -p0 ${G_SOURCE} patch/binutils-2.22-android.patch
	botbrew_import
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			cp -rlf ../${G_SOURCE}/* ./
			CC="agcc.bash" CPPFLAGS="-I${G_INCDIR} -DNO_GECOS_IN_PWENT" LD="agcc.bash" LDFLAGS="-I${G_LIBDIR}" \
			./configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET}
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* ${G_EXPORT}/system/libexec/git-core/* || true
		botbrew_fix_shell_path $(grep -rlIF '/bin/sh' ${G_EXPORT})
		local HASH=$(md5sum ${G_EXPORT}/system/bin/git)
		local HASH=${HASH%%\ *}
		for item in ${G_EXPORT}/system/libexec/git-core/*; do
			if [ -f "${item}" ]; then
				local HASH0=$(md5sum "$item")
				local HASH0=${HASH0%%\ *}
				if [ "${HASH}" = "${HASH0}" ]; then
					echo "Softening link \`${item}'"
					rm ${item}
					ln -s git ${item}
				fi
			fi
		done
		touch ${G_EXPORT}/.d
	fi
}
