#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.7.10.rc3
PACKAGE_DEPEND=( openssl )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://git-core.googlecode.com/files/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_patchtree -p0 ${G_SOURCE} patch/git-1.7.10.rc3.patch
	botbrew_import
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			cp -rlf ../${G_SOURCE}/* ./
			ac_cv_fread_reads_directories=yes \
			ac_cv_snprintf_returns_bogus=yes \
			CPPFLAGS="${G_CPPFLAGS} -I${G_INCDIR} -DNO_GECOS_IN_PWENT" CFLAGS="${G_ALL_CFLAGS}" LDFLAGS="-I${G_LIBDIR}" \
			./configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET}
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* ${G_EXP_SYSDIR}/libexec/git-core/* || true
		botbrew_fix_interpreter_path ${G_EXPORT}
		local HASH=$(md5sum ${G_EXP_BINDIR}/git)
		local HASH=${HASH%%\ *}
		for item in ${G_EXP_SYSDIR}/libexec/git-core/*; do
			if [ -f "${item}" ]; then
				local HASH0=$(md5sum "$item")
				local HASH0=${HASH0%%\ *}
				if [ "${HASH}" = "${HASH0}" ]; then
					echo "Softening link \`${item}'"
					rm ${item}
					ln -s git ${item}
				fi
			fi
		done
		touch ${G_EXPORT}/.d
	fi
}
