#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.5.0
PACKAGE_DEPEND=( libpng lcms )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_svn http://${PACKAGE_NAME}.googlecode.com/svn/trunk ${PACKAGE_NAME}
	botbrew_copytree ${PACKAGE_NAME} ${G_SOURCE} || true
	botbrew_import
	if ! [ -e ${G_SOURCE}/configure ]; then
		(cd ${G_SOURCE}; ./bootstrap.sh)
	fi
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			# libtiff support seems to be broken
			CC="agcc.bash" LD="agcc.bash" LDFLAGS="-L${G_LIBDIR}" \
			PNG_CFLAGS="-I${G_INCDIR}/libpng15" PNG_LIBS="-lpng15 -lz" \
			LCMS2_CFLAGS="-I${G_INCDIR}" LCMS2_LIBS="-llcms2" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET}
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		rm -r ${G_EXPORT}/system/lib/*.la ${G_EXPORT}/system/lib/pkgconfig
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* || true
		touch ${G_EXPORT}/.d
	fi
}
