#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=5.9
PACKAGE_DEPEND=()

FULLNAME=ncurses-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://ftp.gnu.org/gnu/${PACKAGE_NAME}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_patchtree -p0 ${G_SOURCE} patch/ncurses-5.9-android.patch
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CC="agcc.bash" CXX="agcc-bash-g++" LD="agcc.bash" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
				--with-shared --enable-termcap --enable-widec
			# nb: Android's broken locale implementation results in errors such as
			#     'struct lconv' has no member named 'decimal_point'
			# fix: undefine HAVE_LOCALE_H in include/ncurses_cfg.h
			sed -e 's/#define HAVE_LOCALE_H 1//' include/ncurses_cfg.h > temp
			mv temp include/ncurses_cfg.h
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		for file in ${G_EXPORT}/system/lib/*.so.${PACKAGE_VERSION}; do
			mv -T "${file}" "${file%.${PACKAGE_VERSION}}"
		done
		rm -f ${G_EXPORT}/system/lib/*.so.*
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* ${G_EXPORT}/system/lib/*.so || true
		botbrew_fix_shell_path $(grep -rlIF '/bin/sh' ${G_EXPORT})
		touch ${G_EXPORT}/.d
	fi
}
