#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=2.0.7
PACKAGE_DEPEND=()

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://ftp.gnu.org/gnu/${PACKAGE_NAME}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			# arm-linux-androideabi not supported, even with recent config
			CC="${G_TRIPLET}-gcc" LD="${G_TRIPLET}-gcc" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=arm-android-eabi
			sed -e 's/\bsys\/signal\.h\b/asm\/signal.h/' pth.h > temp
			mv temp pth.h
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT} -j1 pth_p.h	# dependency for concurrent builds
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} -j1 install DESTDIR=$(pwd)/${G_EXPORT}
		botbrew_fix_interpreter_path ${G_EXPORT}
		touch ${G_EXPORT}/.d
	fi
}
