#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=2.24.0
PACKAGE_DEPEND=( glib libffi libiconv gettext libtiff jpeg libpng )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.xz

botbrew_do_build() {
	botbrew_download http://ftp.gnome.org/pub/gnome/sources/${PACKAGE_NAME}/${PACKAGE_VERSION%.*}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_fix_config ${G_SOURCE}
	sed -E 's/as_fn_error (\$\? "cannot run test program)/$as_echo \1/g' ${G_SOURCE}/configure > temp
	cat temp > ${G_SOURCE}/configure
	sed -E 's/\$\(SHELL\) \.\/config\.status --recheck/touch $@/g' ${G_SOURCE}/Makefile.in > temp
	mv temp ${G_SOURCE}/Makefile.in
	botbrew_import
	rm -f ${G_IMPORT}/system/lib/libpng.a
	ln -s libpng15.a ${G_IMPORT}/system/lib/libpng.a
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CC="agcc.bash" CPPFLAGS="-I${G_INCDIR} -I${G_INCDIR}/libpng15" \
			LD="agcc.bash" LDFLAGS="-L${G_LIBDIR}" LIBS="-lffi -liconv -lintl" \
			BASE_DEPENDENCIES_CFLAGS="-I${G_INCDIR}" BASE_DEPENDENCIES_LIBS="-L${G_LIBDIR}" \
			GDK_PIXBUF_XLIB_DEP_CFLAGS="-I${G_INCDIR}" GDK_PIXBUF_XLIB_DEP_LIBS="-L${G_LIBDIR}" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET}
			for item in $(grep -rlIF lrt .); do
				sed -e 's/-lrt//g' ${item} > temp
				cat temp > ${item}
			done
			rm temp
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		rm -r ${G_EXPORT}/system/lib/*.la ${G_EXPORT}/system/lib/pkgconfig
		rm $(find ${G_EXPORT}/system/lib -type f -name '*.la')
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* || true
		touch ${G_EXPORT}/.d
	fi
}
