#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=4.5
PACKAGE_DEPEND=()

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://www.jimpryor.net/linux/releases/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	if ! [ -e ${G_SOURCE}/.do.sh ]; then
		for item in $(grep -rlIF '/bin/sh' ${G_SOURCE}/*.c); do
			sed -e 's/\/bin\/sh/\/system\/bin\/sh/g' ${item} > temp
			mv temp ${item}
		done
		touch ${G_SOURCE}/.do.sh
	fi
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			cp -rlf ../${G_SOURCE}/* ./
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT} \
			CC=${G_TRIPLET}-gcc \
			CPPFLAGS='-DTMPDIR=\"/botbrew/tmp\"' \
			PREFIX=${G_INSTALLPREFIX} \
			SBINDIR=${G_INSTALLPREFIX}/bin \
			MANDIR=${G_INSTALLPREFIX}/share/man \
			CRONTABS=${G_INSTALLPREFIX}/var/spool/cron/crontabs \
			CRONSTAMPS=${G_INSTALLPREFIX}/var/spool/cron/cronstamps \
			SCRONTABS=${G_INSTALLPREFIX}/etc/cron.d \
			CRONTAB_GROUP=root
		fakeroot ${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		cp -a ${G_OBJECT}/extra/run-cron ${G_EXP_BINDIR}/
		${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* || true
		botbrew_fix_interpreter_path ${G_EXPORT}
		touch ${G_EXPORT}/.d
	fi
}
