#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=0.3.7
PACKAGE_DEPEND=( pth libiconv curl openssl ncursesw gnutls gmp nettle libtasn1 libgcrypt libgpg-error musl )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://www.weechat.org/files/src/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_fix_config ${G_SOURCE}
	botbrew_patchtree -p0 ${G_SOURCE} patch/weechat-0.3.7-android.patch
	botbrew_import
	rm -f ${G_IMPORT}${G_INSTALLPREFIX}/lib/*.la
	botbrew_fix_crosslibconfig ${G_IMPORT}${G_INSTALLPREFIX}/bin/pth-config
	botbrew_fix_crosslibconfig ${G_IMPORT}${G_INSTALLPREFIX}/bin/curl-config
	botbrew_fix_crosslibconfig ${G_IMPORT}${G_INSTALLPREFIX}/bin/ncursesw5-config
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			CWD=$(pwd)
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			ac_cv_lib_iconv_iconv_open=yes \
			ac_cv_lib_iconv_libiconv_open=yes \
			ac_cv_path_CURL_CONFIG=${CWD}/${G_IMPORT}${G_INSTALLPREFIX}/bin/curl-config \
			CPPFLAGS="${G_CPPFLAGS} -I${G_INCDIR} -I${G_INCDIR}/musl" CFLAGS="${G_ALL_CFLAGS}" \
			LDFLAGS="-L${G_LIBDIR} -Wl,-rpath-link,${G_LIBDIR} -lgnutls -lgcrypt -lmusl" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
				--with-libpth-prefix=${G_SYSDIR} \
				--with-libiconv-prefix=${G_SYSDIR}
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* ${G_EXP_LIBDIR}/weechat/plugins/*.so* || true
		touch ${G_EXPORT}/.d
	fi
}
