#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=0.9.13
PACKAGE_DEPEND=( libbotbrew xorg-proto xorg-lib xcb xorg-lib-libxau jpeg )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://downloads.sourceforge.net/project/libvncserver/${PACKAGE_NAME}/${PACKAGE_VERSION}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_fix_config ${G_SOURCE}
	botbrew_patchtree -p0 ${G_SOURCE} patch/x11vnc-0.9.13-android.patch
	botbrew_import
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			SRCPATH=$(pwd)/${G_SOURCE}
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CC="agcc.bash" CPPFLAGS="-I${G_INCDIR} -I${SRCPATH}" \
			LD="agcc.bash" LDFLAGS="-L${G_LIBDIR}" LIBS="-lxcb -lXau -lbotbrew" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET}
			cat rfb/rfbconfig.h \
				| sed -e 's/#define LIBVNCSERVER_NEED_INADDR_T  1//g' \
				| sed -e 's/#define LIBVNCSERVER_HAVE_PWD_H  1//g' \
				> temp
			mv temp rfb/rfbconfig.h
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* || true
		touch ${G_EXPORT}/.d
	fi
}
