#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=5.2.0
PACKAGE_DEPEND=( readline ncursesw )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://www.lua.org/ftp/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_patchtree -p0 ${G_SOURCE} patch/lua-5.2.0-android.patch
	botbrew_import
	botbrew_fix_crosslibconfig ${G_IMPORT}/system/bin/ncursesw5-config
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			cp -rlf ../${G_SOURCE}/* ./
			sed -e 's/ncurses/ncursesw/g' src/Makefile > temp
			mv temp src/Makefile
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT} PLAT="linux" \
			CC="agcc.bash" CPPFLAGS="-I${G_INCDIR}" LDFLAGS="-L${G_LIBDIR}"
		${G_MAKE} -C ${G_OBJECT} install INSTALL_TOP=$(pwd)/${G_EXPORT}/system INSTALL_MAN=$(pwd)/${G_EXPORT}/system/share/man/man1
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* || true
		touch ${G_EXPORT}/.d
	fi
}
