#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.2.1
PACKAGE_DEPEND=()

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://www.tcpdump.org/release/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_fix_config ${G_SOURCE}
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CC="agcc.bash" LD="agcc.bash" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
				--with-pcap=linux
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		mv ${G_EXPORT}/system/lib/libpcap.so.${PACKAGE_VERSION} ${G_EXPORT}/system/lib/libpcap.so
		rm ${G_EXPORT}/system/lib/libpcap.so.*
		botbrew_fix_shell_path $(grep -rlIF '/bin/sh' ${G_EXPORT})
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/lib/*.so || true
		touch ${G_EXPORT}/.d
	fi
}
