#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=ImageMagick
PACKAGE_VERSION=6.7.5-3
PACKAGE_DEPEND=( jpeg libpng openjpeg libtiff jbig2dec xz bzip2 lcms freetype )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://www.imagemagick.org/download/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_patchtree -p0 ${G_SOURCE} patch/ImageMagick-6.7.5-1-android.patch
	botbrew_import
	botbrew_fix_crosslibconfig ${G_IMPORT}/system/bin/freetype-config
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CC="agcc.bash" CXX="agcc-bash-g++" CPPFLAGS="-I${G_INCDIR} -I${G_INCDIR}/libpng15" \
			LD="agcc.bash" LDFLAGS="-L${G_LIBDIR}" \
			LZMA_CFLAGS="-I${G_INCDIR}" LZMA_LIBS="-llzma" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET}
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		rm -r ${G_EXPORT}/system/lib/*.la ${G_EXPORT}/system/lib/pkgconfig
		${G_STRIP} ${G_EXPORT}/system/bin/* || true
		botbrew_fix_shell_path $(grep -rlIF '/bin/sh' ${G_EXPORT})
		touch ${G_EXPORT}/.d
	fi
}
