#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=7.24.0
PACKAGE_DEPEND=( openssl )

botbrew_do_build() {
	botbrew_git git://github.com/bagder/${PACKAGE_NAME}.git ${PACKAGE_NAME}
	botbrew_copytree ${PACKAGE_NAME} ${G_SOURCE} || true
	botbrew_import
	if ! [ -e ${G_SOURCE}/configure ]; then
		(cd ${G_SOURCE}; ./buildconf)
	fi
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			# shared curl requires shared OpenSSL, which conflicts with Android's shared OpenSSL
			CC="agcc.bash" CPPFLAGS="-I${G_INCDIR}" LD="agcc.bash" LDFLAGS="-L${G_LIBDIR}" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
				--disable-shared --enable-threaded-resolver --with-ssl --with-ca-path=/system/etc/ssl/certs
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
#		for file in ${G_EXPORT}/system/lib/*.so.*.*; do
#			mv -T "${file}" "${file%.*.*}"
#		done
		rm -rf ${G_EXPORT}/system/lib/*.so.* ${G_EXPORT}/system/lib/*.la ${G_EXPORT}/system/lib/pkgconfig
#		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/lib/*.so || true
		botbrew_fix_shell_path $(grep -rlIF '/bin/sh' ${G_EXPORT})
		touch ${G_EXPORT}/.d
	fi
}
