#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=7.24.0
PACKAGE_DEPEND=( openssl )

botbrew_do_build() {
	botbrew_git git://github.com/bagder/${PACKAGE_NAME}.git ${PACKAGE_NAME}
	botbrew_copytree ${PACKAGE_NAME} ${G_SOURCE} || true
	botbrew_import
	if ! [ -e ${G_SOURCE}/configure ]; then
		(cd ${G_SOURCE}; ./buildconf)
	fi
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CPPFLAGS="-I${G_INCDIR}" CFLAGS="${G_CFLAGS} ${G_OFLAGS}" LDFLAGS="-L${G_LIBDIR} -Wl,-rpath,${G_LIBDIR}" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
				--enable-threaded-resolver --with-ssl --with-ca-path=/system/etc/ssl/certs
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* ${G_EXPORT}/system/lib/*.so.* || true
		botbrew_fix_interpreter_path ${G_EXPORT}
		touch ${G_EXPORT}/.d
	fi
}
