#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=2.0.0-beta10
PACKAGE_DEPEND=()

FULLNAME=LuaJIT-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
    botbrew_download http://luajit.org/download/${ARCHIVE} ${ARCHIVE}
    botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
    botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
    botbrew_import
    if ! [ -e ${G_EXPORT}/.d ]; then
        ${G_MAKE} -C ${G_SOURCE} HOST_CC="gcc -m32" CROSS="${G_TRIPLET}-" TARGET_FLAGS="--sysroot ${G_SYSROOT}" TARGET_CFLAGS="${G_ALL_CFLAGS}" TARGET="arm" PREFIX="${G_INSTALLPREFIX}"
        rm ${G_SOURCE}/src/luajit
        ${G_MAKE} -C ${G_SOURCE} HOST_CC="gcc -m32" CROSS="${G_TRIPLET}-" TARGET_FLAGS="--sysroot ${G_SYSROOT}" TARGET_CFLAGS="${G_ALL_CFLAGS}" TARGET="arm" PREFIX="${G_INSTALLPREFIX}" BUILDMODE="dynamic"
        ${G_MAKE} -C ${G_SOURCE} install LDCONFIG=true PREFIX="${G_INSTALLPREFIX}" DESTDIR=$(pwd)/${G_EXPORT}
        ln -sf luajit-$PACKAGE_VERSION $(pwd)/${G_EXPORT}${G_INSTALLPREFIX}/bin/luajit
    fi
}
