#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=2012.55
PACKAGE_DEPEND=( musl )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz
PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp"

botbrew_do_build() {
	botbrew_download http://matt.ucc.asn.au/${PACKAGE_NAME}/releases/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_fix_config ${G_SOURCE}
	botbrew_patchtree -p0 ${G_SOURCE} patch/dropbear-2012.55-android.patch
	botbrew_import
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CPPFLAGS="-D_GNU_SOURCE -I${G_INCDIR}/musl" LDFLAGS="-L${G_LIBDIR}" LIBS="-lmusl" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
				--disable-wtmp \
				--disable-wtmpx \
				--disable-lastlog
			sed -e 's/^#define HAVE_GETUSERSHELL.*//g' config.h > temp
			mv temp config.h
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT} PROGRAMS="${PROGRAMS}" SCPPROGRESS=1 MULTI=1
		${G_MAKE} -C ${G_OBJECT} installdropbearmulti DESTDIR=$(pwd)/${G_EXPORT} PROGRAMS="${PROGRAMS}" SCPPROGRESS=1 MULTI=1
		mv ${G_EXPORT}/system/sbin/* ${G_EXPORT}/system/bin/
		rm -rf ${G_EXPORT}/system/sbin
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* || true
		touch ${G_EXPORT}/.d
	fi
}
