#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=${AGCC_API}
PACKAGE_DEPEND=()

botbrew_do_build() {
	if ! [ -e ${G_EXPORT}/.d ]; then
		mkdir -p ${G_EXPORT}/system/lib
		cp -r ${AGCC_NDK}/platforms/android-${PACKAGE_VERSION}/arch-arm/usr/include ${G_EXPORT}/system/
		cp -r ${AGCC_NDK}/platforms/android-${PACKAGE_VERSION}/arch-arm/usr/lib/*.a ${G_EXPORT}/system/lib/
		cp -r ${AGCC_NDK}/platforms/android-${PACKAGE_VERSION}/arch-arm/usr/lib/*.o ${G_EXPORT}/system/lib/
		touch ${G_EXPORT}/.d
	fi
}

botbrew_do_clobber() {
	rm -rf ${G_OBJECT} ${G_IMPORT} ${G_EXPORT}
}
