#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.19.4
PACKAGE_DEPEND=( musl )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.bz2

botbrew_do_build() {
	botbrew_download http://busybox.net/downloads/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_patchtree -p0 ${G_SOURCE} patch/busybox-1.19.4-android.patch
	botbrew_import
	rm -f ${G_LIBDIR}/libmusl.so*
	if ! [ -e ${G_IMPORT}/.do.private ]; then
		cp patch/*.h ${G_IMPORT_PREFIX}/include/
		touch ${G_IMPORT}/.do.private
	fi
	sed -e 's/crypt//g' ${G_SOURCE}/Makefile.flags > temp
	mv temp ${G_SOURCE}/Makefile.flags
	if ! [ -e ${G_OBJECT}/.config ]; then
		(
			local SRC=$(pwd)/${G_SOURCE}
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			make KBUILD_SRC="${SRC}" -f "${SRC}/Makefile" defconfig
			sleep 1
			cp ../patch/musl.config .config
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		echo ${G_CFLAGS} ${G_OFLAGS}
		${G_MAKE} -C ${G_OBJECT} install CONFIG_PREFIX=$(pwd)/${G_EXPORT} \
			CROSS_COMPILE="${G_TRIPLET}-" \
			CONFIG_EXTRA_CFLAGS="${G_CPPFLAGS} ${G_CFLAGS} ${G_OFLAGS} -I${G_INCDIR} -I${G_INCDIR}/musl -L${G_LIBDIR}" \
			LDLIBS="musl m"
		mkdir -p ${G_EXP_BINDIR} ${G_EXP_LIBDIR} ${G_EXP_SYSDIR}/libexec/busybox
		mv ${G_EXPORT}/bin/busybox ${G_EXP_BINDIR}/
		for item in ${G_EXPORT}/bin/* ${G_EXPORT}/sbin/* ${G_EXPORT}/usr/*/*; do
			ln -s ../bin/busybox "${G_EXP_SYSDIR}/libexec/busybox/${item##*/}" || true
		done
		rm -rf ${G_EXPORT}/bin ${G_EXPORT}/sbin ${G_EXPORT}/usr ${G_EXPORT}/linuxrc
		cp ${G_OBJECT}/0_lib/busybox ${G_EXP_BINDIR}/
		cp ${G_OBJECT}/0_lib/libbusybox.so.${PACKAGE_VERSION} ${G_EXP_LIBDIR}/
		ln -s libbusybox.so.${PACKAGE_VERSION} ${G_EXP_LIBDIR}/libbusybox.so
		${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* ${G_EXP_LIBDIR}/*.so* || true
		touch ${G_EXPORT}/.d
	fi
}
