#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=2.1.1
PACKAGE_DEPEND=()

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://smarden.org/${PACKAGE_NAME}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/admin/${FULLNAME} ${G_SOURCE} || true
	botbrew_patchtree -p0 ${G_SOURCE}/src patch/runit-2.1.1-android.patch
	if ! [ -e ${G_OBJECT}/.d ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			cp -rlf ../${G_SOURCE}/* ./
			cd src
			echo "${G_TRIPLET}-gcc" > conf-cc
			echo "${G_TRIPLET}-gcc -s" > conf-ld
			${G_MAKE} -j1	compile load choose
			cp iopause.h2	iopause.h
			cp uint64.h2	uint64.h
			${G_MAKE} -j1	chkshsgr
			cp hasshsgr.h2	hasshsgr.h
			sed -e 's/static/shared/g' Makefile > temp
			mv temp Makefile
			touch ../.d
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}/src
		mkdir -p ${G_EXP_BINDIR} ${G_EXP_SYSDIR}/share/man ${G_EXP_SYSDIR}/share/doc
		cp -lf \
			${G_OBJECT}/src/chpst \
			${G_OBJECT}/src/runit \
			${G_OBJECT}/src/runit-init \
			${G_OBJECT}/src/runsv \
			${G_OBJECT}/src/runsvchdir \
			${G_OBJECT}/src/runsvdir \
			${G_OBJECT}/src/sv \
			${G_OBJECT}/src/svlogd \
			${G_OBJECT}/src/utmpset \
			${G_EXP_BINDIR}/
		cp -rlf ${G_OBJECT}/src/../man	${G_EXP_SYSDIR}/share/man/man8
		cp -rlf ${G_OBJECT}/src/../doc	${G_EXP_SYSDIR}/share/doc/runit
		${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* || true
		touch ${G_EXPORT}/.d
	fi
}
