#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=2.0.3
PACKAGE_DEPEND=( libgpg-error )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.bz2

botbrew_do_build() {
	botbrew_download ftp://ftp.gnupg.org/gcrypt/${PACKAGE_NAME}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_import
	botbrew_fix_crosslibconfig ${G_IMPORT}${G_INSTALLPREFIX}/bin/gpg-error-config
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CPPFLAGS="${G_CPPFLAGS}" CFLAGS="${G_ALL_CFLAGS}" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
				--with-gpg-error-prefix=${G_SYSDIR}
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		${G_STRIP} --strip-unneeded ${G_EXP_LIBDIR}/*.so* || true
		botbrew_fix_interpreter_path ${G_EXPORT}
		touch ${G_EXPORT}/.d
	fi
}
