#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.0.6
PACKAGE_DEPEND=()

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://bzip.org/${PACKAGE_VERSION}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		mkdir -p ${G_OBJECT}
		cp -rlf ${G_SOURCE}/* ${G_OBJECT}/
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT} install \
			CC="${G_TRIPLET}-gcc" CFLAGS="${G_CPPFLAGS} ${G_ALL_CFLAGS}" PREFIX=$(pwd)/${G_EXPORT}
		${G_MAKE} -C ${G_OBJECT} -f Makefile-libbz2_so all \
			CC="${G_TRIPLET}-gcc" CFLAGS="${G_CPPFLAGS} ${G_ALL_CFLAGS}"
		cp -lf ${G_OBJECT}/bzip2-shared ${G_EXPORT}/bin/
		cp -lf ${G_OBJECT}/libbz2.so* ${G_EXPORT}/lib/
		ln -s libbz2.so.${PACKAGE_VERSION} ${G_EXPORT}/lib/libbz2.so
		mkdir -p ${G_EXP_SYSDIR}/share
		mv ${G_EXPORT}/bin ${G_EXPORT}/include ${G_EXPORT}/lib ${G_EXP_SYSDIR}/
		mv ${G_EXPORT}/man ${G_EXP_SYSDIR}/share/
		botbrew_fix_interpreter_path ${G_EXPORT} || true
		(
			cd ${G_EXP_BINDIR}
			ln -sf bzdiff bzcmp
			ln -sf bzgrep bzegrep
			ln -sf bzgrep bzfgrep
			ln -sf bzmore bzless
		)
		${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* ${G_EXP_LIBDIR}/*.so* || true
		touch ${G_EXPORT}/.d
	fi
}
