#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.0.6
PACKAGE_DEPEND=()

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://bzip.org/${PACKAGE_VERSION}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		mkdir -p ${G_OBJECT}
		cp -rlf ${G_SOURCE}/* ${G_OBJECT}/
		cat ${G_OBJECT}/Makefile-libbz2_so \
			| sed -e 's/\blibbz2\.so[0123456789\.]*/libbz2.so/g' \
			| sed -e 's/rm \-f libbz2\.so//g' \
			| sed -e 's/ln \-s libbz2\.so libbz2\.so//g' \
			> temp
		mv temp ${G_OBJECT}/Makefile-libbz2_so
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT} CC="agcc.bash" LD="agcc.bash" PREFIX=$(pwd)/${G_EXPORT} install
		${G_MAKE} -C ${G_OBJECT} -f Makefile-libbz2_so CC="agcc.bash" all
		cp -lf ${G_OBJECT}/bzip2-shared ${G_EXPORT}/bin/
		cp -lf ${G_OBJECT}/libbz2.so ${G_EXPORT}/lib/
		mkdir -p ${G_EXPORT}/system/share
		mv ${G_EXPORT}/bin ${G_EXPORT}/include ${G_EXPORT}/lib ${G_EXPORT}/system/
		mv ${G_EXPORT}/man ${G_EXPORT}/system/share/
		botbrew_fix_shell_path $(grep -rlIF '/bin/sh' ${G_EXPORT}) || true
		(
			cd ${G_EXPORT}/system/bin
			ln -sf bzdiff bzcmp
			ln -sf bzgrep bzegrep
			ln -sf bzgrep bzfgrep
			ln -sf bzmore bzless
		)
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* ${G_EXPORT}/system/lib/*.so || true
		touch ${G_EXPORT}/.d
	fi
}
