#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=0.0.1
PACKAGE_DEPEND=( xorg-proto xorg-lib-libxau xcb freetype )

local DLPREFIX=http://ftp.x.org/pub/individual/lib
local PART=(
	xtrans-1.2.6
	libXdmcp-1.1.0
	libX11-1.4.99.1
	libXrender-0.9.6
	libXext-1.3.0
	libXi-1.5.99.3
	libXtst-1.2.0
	libICE-1.0.7
	libSM-1.2.0
	libXt-1.1.1
	libxkbfile-1.0.7
	libxkbui-1.0.2
	liblbxutil-1.1.0
	libXxf86misc-1.0.3
	libfontenc-1.1.0
	libXfont-1.4.4
	libpciaccess-0.12.902
	libXfixes-5.0
	libXmu-1.1.0
)

botbrew_do_build() {
	mkdir -p ${G_OBJECT} ${G_SOURCE} ${G_EXPORT}
	botbrew_import
	botbrew_fix_crosslibconfig ${G_IMPORT}/system/bin/freetype-config
	local CWD=$(pwd)
	local INCFLAGS="-I${G_INCDIR} -I${G_INCDIR}/freetype2 -I$(pwd)/${G_EXPORT}/system/include"
	local LIBFLAGS="-L${G_LIBDIR} -L$(pwd)/${G_EXPORT}/system/lib"
	for item in ${PART[@]}; do
		botbrew_download ${DLPREFIX}/${item}.tar.bz2 ${item}.tar.bz2
		botbrew_unpack ${item}.tar.bz2 ${item} || true
		botbrew_copytree ${item}/${item} ${G_SOURCE}/${item} || true
		botbrew_fix_config ${G_SOURCE}/${item}
		case ${item} in
			xtrans-*)
				botbrew_patchtree -p0 ${G_SOURCE}/${item} patch/xtrans-1.2.6-android.patch
				;;
			libX11-*)
				sed -i 's/^KEYSYMDEFDIR=.*//g' ${G_SOURCE}/${item}/configure
				botbrew_patchtree -p0 ${G_SOURCE}/${item} patch/libX11-1.4.99.1-android.patch
				;;
			libICE-*)
				botbrew_patchtree -p0 ${G_SOURCE}/${item} patch/libICE-1.0.7-android.patch
				;;
			libXt-*)
				botbrew_patchtree -p0 ${G_SOURCE}/${item} patch/libXt-1.1.1-android.patch
				;;
			libpciaccess-*)
				botbrew_patchtree -p0 ${G_SOURCE}/${item} patch/libpciaccess-0.12.902-android.patch
				;;
			libXmu-*)
				botbrew_patchtree -p0 ${G_SOURCE}/${item} patch/libXmu-1.1.0-android.patch
				;;
		esac
		if ! [ -e ${G_OBJECT}/${item}/Makefile ]; then
			(
				mkdir -p ${G_OBJECT}/${item}; cd ${G_OBJECT}/${item}
				CC="agcc.bash" LD="agcc.bash" \
				XTRANS_CFLAGS="${INCFLAGS}" XTRANS_LIBS="${LIBFLAGS}" \
				XDMCP_CFLAGS="${INCFLAGS}" XDMCP_LIBS="${LIBFLAGS}" \
				X11_CFLAGS="${INCFLAGS}" X11_LIBS="${LIBFLAGS}" \
				RENDER_CFLAGS="${INCFLAGS}" RENDER_LIBS="${LIBFLAGS}" \
				XEXT_CFLAGS="${INCFLAGS}" XEXT_LIBS="${LIBFLAGS}" \
				XI_CFLAGS="${INCFLAGS}" XI_LIBS="${LIBFLAGS}" \
				XTST_CFLAGS="${INCFLAGS}" XTST_LIBS="${LIBFLAGS}" \
				ICE_CFLAGS="${INCFLAGS}" ICE_LIBS="${LIBFLAGS}" \
				SM_CFLAGS="${INCFLAGS}" SM_LIBS="${LIBFLAGS}" \
				XT_CFLAGS="${INCFLAGS}" XT_LIBS="${LIBFLAGS}" \
				XKBFILE_CFLAGS="${INCFLAGS}" XKBFILE_LIBS="${LIBFLAGS}" \
				XKBUI_CFLAGS="${INCFLAGS}" XKBUI_LIBS="${LIBFLAGS}" \
				LBXUTIL_CFLAGS="${INCFLAGS}" LBXUTIL_LIBS="${LIBFLAGS}" \
				XXF86MISC_CFLAGS="${INCFLAGS}" XXF86MISC_LIBS="${LIBFLAGS}" \
				FONTENC_CFLAGS="${INCFLAGS}" FONTENC_LIBS="${LIBFLAGS}" \
				FREETYPE_CFLAGS="${INCFLAGS}" FREETYPE_LIBS="${LIBFLAGS}" \
				XFONT_CFLAGS="${INCFLAGS}" XFONT_LIBS="${LIBFLAGS}" \
				FIXESEXT_CFLAGS="${INCFLAGS}" FIXESEXT_LIBS="${LIBFLAGS}" \
				XMU_CFLAGS="${INCFLAGS}" XMU_LIBS="${LIBFLAGS}" \
				XMUU_CFLAGS="${INCFLAGS}" XMUU_LIBS="${LIBFLAGS}" \
				KEYSYMDEFDIR="${G_INCDIR}/X11" \
				../../${G_SOURCE}/${item}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET}
				case ${item} in
					libXdmcp-*|libICE-*|libSM-*|libXt-*|libxkbfile-*)
						sed -i '1i #include <strings.h>' config.h
						;;
					liblbxutil-*)
						${G_MAKE} -C src mkg3states CC="gcc"
						sed -i '1i #include <strings.h>' config.h
						;;
					libX11-*)
						sed -i '1i #include <strings.h>' src/config.h
						;;
					libXfont-*)
						echo "#define NO_LOCALE 1" >> config.h
				esac
				sed -i 's/^.*config\.status --recheck.*//g' Makefile
			)
		fi
		if ! [ -e ${G_EXPORT}/.d.${item} ]; then
			${G_MAKE} -C ${G_OBJECT}/${item}
			${G_MAKE} -C ${G_OBJECT}/${item} install DESTDIR=${CWD}/${G_EXPORT}
			touch ${G_EXPORT}/.d.${item}
		fi
	done
	rm -r ${G_EXPORT}/system/lib/*.la ${G_EXPORT}/system/lib/pkgconfig
	touch ${G_EXPORT}/.d
}
