#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=xorg-server
PACKAGE_VERSION=1.11.99.903
PACKAGE_DEPEND=( pixman xorg-proto xorg-lib xorg-lib-libxau freetype bzip2 libcpufeatures libbotbrew )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.bz2

botbrew_do_build() {
	botbrew_download http://ftp.x.org/pub/individual/xserver/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_patchtree -p0 ${G_SOURCE} patch/xorg-server-1.11.99.903-android.patch
	botbrew_import
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CC="agcc.bash" LD="agcc.bash" \
			PIXMAN_CFLAGS="-I${G_INCDIR}" PIXMAN_LIBS="-L${G_LIBDIR}" \
			XLIB_CFLAGS="-I${G_INCDIR}" XLIB_LIBS="-L${G_LIBDIR}" \
			XSERVERCFLAGS_CFLAGS="-I${G_INCDIR} -I${G_INCDIR}/pixman-1" XSERVERCFLAGS_LIBS="-L${G_LIBDIR}" \
			XSERVERLIBS_CFLAGS="-I${G_INCDIR}" \
			XSERVERLIBS_LIBS="-L${G_LIBDIR} -lpixman-1 -lXau -lXfont -lfontenc -lfreetype -lbz2 -lz -lcpufeatures -lbotbrew" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
				--with-default-font-path=/system/share/fonts/X11/misc/:/system/share/fonts/X11/TTF/:/system/share/fonts/X11/OTF/:/system/share/fonts/X11/Type1/:/system/share/fonts/X11/100dpi/:/system/share/fonts/X11/75dpi/ \
				--with-xkb-bin-directory=/system/bin \
				--disable-pciaccess \
				--disable-xorg \
				--disable-dmx \
				--enable-xvfb \
				--disable-xnest \
				--disable-xquartz \
				--disable-xwin \
				--disable-kdrive \
				--disable-xephyr \
				--disable-xfake \
				--disable-xfbdev \
				--disable-glx \
				--disable-dri \
				--disable-dri2 \
				--disable-xinerama \
				--disable-composite \
				--disable-screensaver
			sed -e 's/-lpthread//g' hw/vfb/Makefile > temp
			mv temp hw/vfb/Makefile
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* || true
		touch ${G_EXPORT}/.d
	fi
}
