#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=0.8
PACKAGE_DEPEND=( musl )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://downloads.sourceforge.net/project/${PACKAGE_NAME}/${PACKAGE_NAME}/${PACKAGE_VERSION}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_import
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CFLAGS="${G_CPPFLAGS} ${G_ALL_CFLAGS} -I${G_INCDIR}/musl" LDFLAGS="-L${G_LIBDIR}" LIBS="-lmusl" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET}
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		mkdir -p ${G_EXP_BINDIR}
		cp ${G_OBJECT}/dtach ${G_EXP_BINDIR}/
		${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* || true
		touch ${G_EXPORT}/.d
	fi
}
