#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.5.12
PACKAGE_DEPEND=( musl expat )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://cgit.freedesktop.org/${PACKAGE_NAME}/${PACKAGE_NAME}/snapshot/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_patchtree -p0 ${G_SOURCE} patch/dbus-1.5.12-android.patch
	botbrew_import
	if ! [ -e ${G_SOURCE}/configure ]; then
		(cd ${G_SOURCE}; ./autogen.sh)
	fi
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CPPFLAGS="${G_CPPFLAGS} -I${G_INCDIR} -I${G_INCDIR}/musl" CFLAGS="${G_ALL_CFLAGS}" \
			LDFLAGS="-L${G_LIBDIR}" LIBS="-lmusl" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
				--disable-modular-tests \
				--disable-tests
			cat doc/Makefile \
				| sed -e 's/install-html-recursive//g' \
				| sed -e 's/^DATA =.*//g' \
				| sed -e 's/^html_DATA =.*//g' \
				| sed -e 's/^dist_html_DATA =.*//g' \
				> temp
			mv temp doc/Makefile
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} -j1 install DESTDIR=$(pwd)/${G_EXPORT}
		sed -e 's/\/tmp/\/botbrew\/tmp/g' ${G_EXP_SYSDIR}/etc/dbus-1/session.conf > temp
		mv temp ${G_EXP_SYSDIR}/etc/dbus-1/session.conf
		${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* ${G_EXP_LIBDIR}/*.so* ${G_EXP_SYSDIR}/libexec/* || true
		touch ${G_EXPORT}/.d
	fi
}
