#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=0.0.1
PACKAGE_DEPEND=()

local DLPREFIX=http://ftp.x.org/pub/individual/proto
local PART=(
	bigreqsproto-1.1.1
	damageproto-1.2.1
	fixesproto-5.0
	fontcacheproto-0.1.3
	fontsproto-2.1.1
	inputproto-2.1.99.6
	kbproto-1.0.5
	randrproto-1.3.2
	recordproto-1.14
	renderproto-0.11
	resourceproto-1.2.0
	videoproto-2.3.1
	xcmiscproto-1.1.2
	xextproto-7.2.0
	xf86miscproto-0.9.3
	xproto-7.0.22
)

botbrew_do_build() {
	mkdir -p ${G_OBJECT} ${G_SOURCE} ${G_EXPORT}
	local CWD=$(pwd)
	for item in ${PART[@]}; do
		botbrew_download ${DLPREFIX}/${item}.tar.bz2 ${item}.tar.bz2
		botbrew_unpack ${item}.tar.bz2 ${item} || true
		botbrew_copytree ${item}/${item} ${G_SOURCE}/${item} || true
		botbrew_fix_config ${G_SOURCE}/${item} || true
		if ! [ -e ${G_OBJECT}/${item}/Makefile ]; then
			(
				mkdir -p ${G_OBJECT}/${item}; cd ${G_OBJECT}/${item}
				CC="agcc.bash" LD="agcc.bash" \
				../../${G_SOURCE}/${item}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET}
			)
		fi
		if ! [ -e ${G_EXPORT}/.d.${item} ]; then
			${G_MAKE} -C ${G_OBJECT}/${item}
			${G_MAKE} -C ${G_OBJECT}/${item} install DESTDIR=${CWD}/${G_EXPORT}
			touch ${G_EXPORT}/.d.${item}
		fi
	done
	if ! [ -e ${G_EXPORT}/.d ]; then
		sed -i '1i #include <strings.h>' ${G_EXPORT}/system/include/X11/Xfuncs.h
		sed -i '1i #include <strings.h>' ${G_EXPORT}/system/include/X11/Xos.h
		rm -rf ${G_EXPORT}/system/lib/pkgconfig
		touch ${G_EXPORT}/.d
	fi
}
