#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=3.0
PACKAGE_DEPEND=()

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
	botbrew_download http://llvm.org/releases/${PACKAGE_VERSION}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME}.src ${G_SOURCE} || true
	botbrew_patchtree -p0 ${G_SOURCE} patch/llvm-3.0-android.patch
	botbrew_download http://llvm.org/releases/${PACKAGE_VERSION}/clang-${PACKAGE_VERSION}.tar.gz clang-${PACKAGE_VERSION}.tar.gz
	botbrew_unpack clang-${PACKAGE_VERSION}.tar.gz clang-${PACKAGE_VERSION} || true
	botbrew_copytree clang-${PACKAGE_VERSION}/clang-${PACKAGE_VERSION}.src ${G_SOURCE}/tools/clang || true
	botbrew_patchtree -p0 ${G_SOURCE}/tools/clang patch/clang-3.0-android.patch
	botbrew_svn http://llvm.org/svn/llvm-project/compiler-rt/trunk compiler-rt
	botbrew_copytree compiler-rt ${G_SOURCE}/projects/compiler-rt || true
	botbrew_svn http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
	botbrew_copytree libcxx ${G_SOURCE}/projects/libcxx || true
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CC="agcc.bash" CXX="agcc-bash-g++" LIBS="-ldl" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} --target=${G_TRIPLET} \
				--enable-shared --with-c-include-dirs=/system/include
			cp -rlf ../${G_SOURCE}/projects/compiler-rt projects/
			cp ../patch/libcompiler_rt_cross_arm.mk projects/compiler-rt/make/platform/cross_arm.mk
			cp -rlf ../${G_SOURCE}/projects/libcxx projects/
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT} REQUIRES_RTTI=1 KEEP_SYMBOLS=1
		${G_MAKE} -C ${G_OBJECT}/tools/clang/runtime/compiler-rt
		${G_MAKE} -C ${G_OBJECT}/tools/clang/runtime/libcxx
		${G_MAKE} -C ${G_OBJECT}/projects/compiler-rt cross_arm
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT} REQUIRES_RTTI=1 KEEP_SYMBOLS=1
		rm -rf ${G_EXPORT}/system/share/doc
		mv ${G_EXPORT}/system/docs ${G_EXPORT}/system/share/doc
		cp -lf ${G_OBJECT}/projects/compiler-rt/cross_arm/Release/arm/*.a ${G_EXPORT}/system/lib/
		chmod +x ${G_EXPORT}/system/lib/* ${G_EXPORT}/system/lib/c++/v1/support
		${G_STRIP} --strip-unneeded ${G_EXPORT}/system/bin/* ${G_EXPORT}/system/lib/*.so || true
		touch ${G_EXPORT}/.d
	fi
}
